# Exploratory Data Analysis of Electricity in Canada

Real dataset is acquired from the government of Canada website.                                                                              https://open.canada.ca/data/en/dataset/2cdf43fc-d4aa-4604-9f21-29777d955810

In [40]:
import pandas as pd

electricity_capacity = pd.read_csv("electricity-capacity-2021.csv")
electricity_generation = pd.read_csv("electricity-generation-2021.csv")
electricity_interchange = pd.read_csv("electricity-interchange-2021.csv")


In [41]:
electricity_generation

Scenario   Region              Variable          Type  Year  \
0       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2005   
1       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2006   
2       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2007   
3       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2008   
4       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2009   
...                  ...      ...                   ...           ...   ...   
10299  Evolving Policies    Yukon                  Wind  Primary Fuel  2046   
10300  Evolving Policies    Yukon                  Wind  Primary Fuel  2047   
10301  Evolving Policies    Yukon                  Wind  Primary Fuel  2048   
10302  Evolving Policies    Yukon                  Wind  Primary Fuel  2049   
10303  Evolving Policies    Yukon                  Wind  Primary Fuel  2050   

           Value  
0      1725.1680  
1      1855.1690  
2      1870.3620  
3      1917.3880  
4      1861.5000  
...          ...  
10299    62.1059  
10300    62.7420  
10301    63.3724  
10302    64.0051  
10303    64.6355  

[10304 rows x 6 columns]

Some quick Visuals of electricity capacity and generation.

In [42]:
_deepnote_run_altair(electricity_generation, """{"data":{"name":"placeholder"},"mark":{"type":"bar","tooltip":true},"height":220,"$schema":"https://vega.github.io/schema/vega-lite/v4.json","autosize":{"type":"fit"},"encoding":{"x":{"sort":null,"type":"nominal","field":"Variable","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"quantitative","field":"Value","scale":{"type":"linear","zero":true}},"color":{"sort":null,"type":"nominal","field":"","scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

In [43]:
_deepnote_run_altair(electricity_generation, """{"data":{"name":"placeholder"},"mark":{"type":"bar","tooltip":true},"height":220,"$schema":"https://vega.github.io/schema/vega-lite/v4.json","autosize":{"type":"fit"},"encoding":{"x":{"bin":false,"sort":null,"type":"quantitative","field":"Value","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"nominal","field":"Region","scale":{"type":"linear","zero":true}},"color":{"sort":null,"type":"nominal","field":"","scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

In [44]:
electricity_capacity

Scenario   Region              Variable          Type  Year  \
0       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2005   
1       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2006   
2       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2007   
3       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2008   
4       Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2009   
...                  ...      ...                   ...           ...   ...   
10299  Evolving Policies    Yukon                  Wind  Primary Fuel  2046   
10300  Evolving Policies    Yukon                  Wind  Primary Fuel  2047   
10301  Evolving Policies    Yukon                  Wind  Primary Fuel  2048   
10302  Evolving Policies    Yukon                  Wind  Primary Fuel  2049   
10303  Evolving Policies    Yukon                  Wind  Primary Fuel  2050   

            Value  
0      271.000000  
1      313.100000  
2      313.100000  
3      313.100000  
4      323.200000  
...           ...  
10299   16.942262  
10300   17.470997  
10301   18.010307  
10302   18.602490  
10303   19.263409  

[10304 rows x 6 columns]

In [45]:
_deepnote_run_altair(electricity_capacity, """{"data":{"name":"placeholder"},"mark":{"type":"bar","tooltip":true},"height":220,"$schema":"https://vega.github.io/schema/vega-lite/v4.json","autosize":{"type":"fit"},"encoding":{"x":{"sort":null,"type":"nominal","field":"Region","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"quantitative","field":"Value","scale":{"type":"linear","zero":true}},"color":{"sort":null,"type":"nominal","field":"","scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

- Between 2016 and 2021, I'm now aiming for both electricity generation value and capacity by applying SQL JOIN. 

In [46]:


df_5 = _deepnote_execute_sql("""SELECT g.region, g.year, g.variable, g.value AS E_generate, c.value AS E_capacity


FROM electricity_generation g
JOIN electricity_capacity c
ON g.Year = c.Year 
    AND g.Region = c.Region 
    AND g.variable = c.variable



WHERE g.year BETWEEN 2016 AND 2021;
-- ORDER BY 4 DESC;
--LIMIT 10;
--WHERE year = 2021 AND Region='Canada' AND variable='Wind';
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_5

Region  Year              Variable  E_generate  E_capacity
0     Alberta  2016  Biomass / Geothermal    2127.448      281.61
1     Alberta  2017  Biomass / Geothermal    1158.511      281.61
2     Alberta  2018  Biomass / Geothermal    1837.126      272.61
3     Alberta  2019  Biomass / Geothermal    1844.108      272.61
4     Alberta  2020  Biomass / Geothermal    1631.825      281.61
...       ...   ...                   ...         ...         ...
2683    Yukon  2017                  Wind       0.000        0.81
2684    Yukon  2018                  Wind       0.000        0.81
2685    Yukon  2019                  Wind       0.000        0.81
2686    Yukon  2020                  Wind       0.000        0.81
2687    Yukon  2021                  Wind       0.000        0.81

[2688 rows x 5 columns]

In [47]:
N_df_5 = df_5.groupby(['Region'])[['E_capacity','E_generate']].max()
N_df_5


E_capacity   E_generate
Region                                            
Alberta                     10289.150   46509.7800
British Columbia            15955.470   66503.0200
Canada                      82307.480  392952.2000
Manitoba                     5449.159   36599.0000
New Brunswick                1593.040    5120.0000
Newfoundland and Labrador    7617.681   50459.1200
Northwest Territories         124.060     426.7098
Nova Scotia                  1252.000    4972.7192
Nunavut                        54.280     274.7424
Ontario                     13568.000   91142.0100
Prince Edward Island          233.280     940.0744
Quebec                      40853.150  201677.6000
Saskatchewan                 2209.960   14977.4600
Yukon                          94.500     448.0000

- So,  I need information on the capacity of the electrical supply from 2005 to 2021. All data saved into df_6 dataframe.

In [48]:


df_6 = _deepnote_execute_sql("""SELECT *
FROM electricity_capacity
where year <  2022;
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_6

Scenario   Region              Variable          Type  Year  \
0      Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2005   
1      Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2006   
2      Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2007   
3      Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2008   
4      Current Policies  Alberta  Biomass / Geothermal  Primary Fuel  2009   
...                 ...      ...                   ...           ...   ...   
3803  Evolving Policies    Yukon                  Wind  Primary Fuel  2017   
3804  Evolving Policies    Yukon                  Wind  Primary Fuel  2018   
3805  Evolving Policies    Yukon                  Wind  Primary Fuel  2019   
3806  Evolving Policies    Yukon                  Wind  Primary Fuel  2020   
3807  Evolving Policies    Yukon                  Wind  Primary Fuel  2021   

       Value  
0     271.00  
1     313.10  
2     313.10  
3     313.10  
4     323.20  
...      ...  
3803    0.81  
3804    0.81  
3805    0.81  
3806    0.81  
3807    0.81  

[3808 rows x 6 columns]

- Basics of df_6 data frame.

In [49]:
print ("Rows     : " , df_6.shape[0])
print ("Columns  : " , df_6.shape[1])
print ("\nFeatures : \n" , df_6.columns.tolist())
print ("\nMissing values :  ", df_6.isnull().sum().values.sum())
print ("\nUnique values :  \n",df_6.nunique())

Rows     :  3808
Columns  :  6

Features : 
 ['Scenario', 'Region', 'Variable', 'Type', 'Year', 'Value']

Missing values :   0

Unique values :  
 Scenario      2
Region       14
Variable      8
Type          1
Year         17
Value       525
dtype: int64


In [50]:
df_6.dtypes

Scenario     object
Region       object
Variable     object
Type         object
Year          int64
Value       float64
dtype: object

In [51]:
df_7 = df_6.groupby(df_6['Region'])['Value'].max()
df_7

Region
Alberta                      10289.150
British Columbia             15955.470
Canada                       82307.480
Manitoba                      5449.159
New Brunswick                 1593.040
Newfoundland and Labrador     7617.681
Northwest Territories          124.060
Nova Scotia                   1288.000
Nunavut                         54.280
Ontario                      13640.000
Prince Edward Island           233.280
Quebec                       40853.150
Saskatchewan                  2209.960
Yukon                           95.200
Name: Value, dtype: float64

In [52]:
df_7.mean()

12979.279285714287

The data for the region, year, and variable column data are  stored into the variables states, years and E_source respectively using Numpy.

In [53]:
import numpy as np

In [54]:
states = np.array(df_6['Region'])
years = np.array(df_6['Year'])
E_source = np.array(df_6['Variable'])

# performed groupby for value.
df_10 = df_6['Value'].groupby([states, years, E_source]).mean()
df_10

Alberta  2005  Biomass / Geothermal     271.000
               Coal & Coke             5696.000
               Hydro / Wave / Tidal     869.000
               Natural Gas             4904.000
               Oil                        7.150
                                         ...   
Yukon    2021  Natural Gas               19.800
               Oil                       24.570
               Solar                      0.044
               Uranium                    0.000
               Wind                       0.810
Name: Value, Length: 1904, dtype: float64

- Simple search for year.

In [55]:
pieces = dict(list(df_6.groupby('Year')))


In [56]:
pieces[2021]


Scenario                Region              Variable  \
16     Current Policies               Alberta  Biomass / Geothermal   
33     Current Policies      British Columbia  Biomass / Geothermal   
50     Current Policies                Canada  Biomass / Geothermal   
67     Current Policies              Manitoba  Biomass / Geothermal   
84     Current Policies         New Brunswick  Biomass / Geothermal   
...                 ...                   ...                   ...   
3739  Evolving Policies               Ontario                  Wind   
3756  Evolving Policies  Prince Edward Island                  Wind   
3773  Evolving Policies                Quebec                  Wind   
3790  Evolving Policies          Saskatchewan                  Wind   
3807  Evolving Policies                 Yukon                  Wind   

              Type  Year        Value  
16    Primary Fuel  2021   281.610000  
33    Primary Fuel  2021   927.790000  
50    Primary Fuel  2021  2298.350000  
67    Primary Fuel  2021    22.000000  
84    Primary Fuel  2021   127.300000  
...            ...   ...          ...  
3739  Primary Fuel  2021  5536.830689  
3756  Primary Fuel  2021   233.280000  
3773  Primary Fuel  2021  4330.102184  
3790  Primary Fuel  2021   221.211724  
3807  Primary Fuel  2021     0.810000  

[224 rows x 6 columns]

### I'm concentrating a lot on the province of Ontario from THIS POINT, including how much electricity is generated there and what proportions of each energy source.

In [57]:


df_9 = _deepnote_execute_sql("""SELECT *
FROM electricity_generation

-- WHERE Region = 'Ontario' AND year = 2021;  Scenario & Variable 
-- WHERE Region = 'Ontario' AND year < 2021;
-- WHERE Region = 'Ontario' AND year > 2021;

 WHERE Region = 'Ontario' AND year BETWEEN 2016 AND 2021;

 --Variable  = 'Wind'
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_9

Scenario   Region              Variable          Type  Year  \
0    Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2016   
1    Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2017   
2    Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2018   
3    Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2019   
4    Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2020   
..                ...      ...                   ...           ...   ...   
91  Evolving Policies  Ontario                  Wind  Primary Fuel  2017   
92  Evolving Policies  Ontario                  Wind  Primary Fuel  2018   
93  Evolving Policies  Ontario                  Wind  Primary Fuel  2019   
94  Evolving Policies  Ontario                  Wind  Primary Fuel  2020   
95  Evolving Policies  Ontario                  Wind  Primary Fuel  2021   

         Value  
0    1444.1490  
1     962.0511  
2    1310.7740  
3    1249.3920  
4     756.0698  
..         ...  
91  10464.0000  
92  11922.0100  
93  10957.0000  
94  14436.8354  
95  15840.4116  

[96 rows x 6 columns]

Distribution of power generation in Ontario as a visual. where the highest concentration of uranium is used to produce power.(years between 2016 to 2021)

In [58]:
_deepnote_run_altair(df_9, """{"data":{"name":"placeholder"},"mark":{"type":"bar","tooltip":true},"height":220,"$schema":"https://vega.github.io/schema/vega-lite/v4.json","autosize":{"type":"fit"},"encoding":{"x":{"sort":null,"type":"nominal","field":"Variable","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"quantitative","field":"Value","scale":{"type":"linear","zero":true}},"color":{"sort":null,"type":"nominal","field":"Variable","scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

In [59]:
functions = ['count', 'mean', 'max', 'sum']

In [60]:
df_9['Value'].sum()

1821069.3399119999

In [61]:
Results = df_9.groupby(['Region' , 'Variable'])['Value'].agg(functions)
Results

count          mean           max           sum
Region  Variable                                                             
Ontario Biomass / Geothermal     12   1080.722417   1444.149000  1.296867e+04
        Coal & Coke              12      0.000000      0.000000  0.000000e+00
        Hydro / Wave / Tidal     12  37894.986667  40201.390000  4.547398e+05
        Natural Gas              12  11798.906167  14862.200000  1.415869e+05
        Oil                      12    326.762150    544.258000  3.921146e+03
        Solar                    12   2073.664509   2169.973112  2.488397e+04
        Uranium                  12  86184.527500  91142.010000  1.034214e+06
        Wind                     12  12396.208917  15840.411600  1.487545e+05

In [62]:
Percentage_results = (Results['sum'] / Results['sum'].sum()) * 100
Percentage_results

Region   Variable            
Ontario  Biomass / Geothermal     0.712146
         Coal & Coke              0.000000
         Hydro / Wave / Tidal    24.971034
         Natural Gas              7.774930
         Oil                      0.215321
         Solar                    1.366448
         Uranium                 56.791595
         Wind                     8.168525
Name: sum, dtype: float64

Hence, The ontario genrated total 56.79 % of electricity from Uranium, fallowed by Hydro/Wave/tidel AND Wind with 24.97 % and 8.16 %.

### Combining electricity generation and capacity data for comparison.

In [63]:


Capacity = _deepnote_execute_sql("""SELECT *
FROM electricity_capacity

 -- WHERE Region = 'Ontario' AND Year = 2017 AND Variable='Solar';
-- WHERE Region = 'Ontario' AND year < 2021;
-- WHERE Region = 'Ontario' AND year > 2021;

 WHERE Scenario='Current Policies' AND Region = 'Ontario' AND year BETWEEN 2016 AND 2021;
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
Capacity

Scenario   Region              Variable          Type  Year  \
0   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2016   
1   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2017   
2   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2018   
3   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2019   
4   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2020   
5   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2021   
6   Current Policies  Ontario           Coal & Coke  Primary Fuel  2016   
7   Current Policies  Ontario           Coal & Coke  Primary Fuel  2017   
8   Current Policies  Ontario           Coal & Coke  Primary Fuel  2018   
9   Current Policies  Ontario           Coal & Coke  Primary Fuel  2019   
10  Current Policies  Ontario           Coal & Coke  Primary Fuel  2020   
11  Current Policies  Ontario           Coal & Coke  Primary Fuel  2021   
12  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2016   
13  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2017   
14  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2018   
15  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2019   
16  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2020   
17  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2021   
18  Current Policies  Ontario           Natural Gas  Primary Fuel  2016   
19  Current Policies  Ontario           Natural Gas  Primary Fuel  2017   
20  Current Policies  Ontario           Natural Gas  Primary Fuel  2018   
21  Current Policies  Ontario           Natural Gas  Primary Fuel  2019   
22  Current Policies  Ontario           Natural Gas  Primary Fuel  2020   
23  Current Policies  Ontario           Natural Gas  Primary Fuel  2021   
24  Current Policies  Ontario                   Oil  Primary Fuel  2016   
25  Current Policies  Ontario                   Oil  Primary Fuel  2017   
26  Current Policies  Ontario                   Oil  Primary Fuel  2018   
27  Current Policies  Ontario                   Oil  Primary Fuel  2019   
28  Current Policies  Ontario                   Oil  Primary Fuel  2020   
29  Current Policies  Ontario                   Oil  Primary Fuel  2021   
30  Current Policies  Ontario                 Solar  Primary Fuel  2016   
31  Current Policies  Ontario                 Solar  Primary Fuel  2017   
32  Current Policies  Ontario                 Solar  Primary Fuel  2018   
33  Current Policies  Ontario                 Solar  Primary Fuel  2019   
34  Current Policies  Ontario                 Solar  Primary Fuel  2020   
35  Current Policies  Ontario                 Solar  Primary Fuel  2021   
36  Current Policies  Ontario               Uranium  Primary Fuel  2016   
37  Current Policies  Ontario               Uranium  Primary Fuel  2017   
38  Current Policies  Ontario               Uranium  Primary Fuel  2018   
39  Current Policies  Ontario               Uranium  Primary Fuel  2019   
40  Current Policies  Ontario               Uranium  Primary Fuel  2020   
41  Current Policies  Ontario               Uranium  Primary Fuel  2021   
42  Current Policies  Ontario                  Wind  Primary Fuel  2016   
43  Current Policies  Ontario                  Wind  Primary Fuel  2017   
44  Current Policies  Ontario                  Wind  Primary Fuel  2018   
45  Current Policies  Ontario                  Wind  Primary Fuel  2019   
46  Current Policies  Ontario                  Wind  Primary Fuel  2020   
47  Current Policies  Ontario                  Wind  Primary Fuel  2021   

        Value  
0     801.300  
1     692.700  
2     692.700  
3     492.700  
4     492.700  
5     492.700  
6       0.000  
7       0.000  
8       0.000  
9       0.000  
10      0.000  
11      0.000  
12   9105.298  
13   9161.298  
14   9161.298  
15   9161.298  
16   9161.298  
17   9161.298  
18   9629.630  
19   9918.631  


In [64]:


Generate = _deepnote_execute_sql("""SELECT * 
--Scenario,Region,Variable, SUM(Value) as sum_genearte
FROM electricity_generation

 WHERE Scenario='Current Policies' AND Region = 'Ontario' AND year BETWEEN 2016 AND 2021
 --GROUP BY Scenario, Region,Variable;
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
Generate

Scenario   Region              Variable          Type  Year  \
0   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2016   
1   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2017   
2   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2018   
3   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2019   
4   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2020   
5   Current Policies  Ontario  Biomass / Geothermal  Primary Fuel  2021   
6   Current Policies  Ontario           Coal & Coke  Primary Fuel  2016   
7   Current Policies  Ontario           Coal & Coke  Primary Fuel  2017   
8   Current Policies  Ontario           Coal & Coke  Primary Fuel  2018   
9   Current Policies  Ontario           Coal & Coke  Primary Fuel  2019   
10  Current Policies  Ontario           Coal & Coke  Primary Fuel  2020   
11  Current Policies  Ontario           Coal & Coke  Primary Fuel  2021   
12  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2016   
13  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2017   
14  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2018   
15  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2019   
16  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2020   
17  Current Policies  Ontario  Hydro / Wave / Tidal  Primary Fuel  2021   
18  Current Policies  Ontario           Natural Gas  Primary Fuel  2016   
19  Current Policies  Ontario           Natural Gas  Primary Fuel  2017   
20  Current Policies  Ontario           Natural Gas  Primary Fuel  2018   
21  Current Policies  Ontario           Natural Gas  Primary Fuel  2019   
22  Current Policies  Ontario           Natural Gas  Primary Fuel  2020   
23  Current Policies  Ontario           Natural Gas  Primary Fuel  2021   
24  Current Policies  Ontario                   Oil  Primary Fuel  2016   
25  Current Policies  Ontario                   Oil  Primary Fuel  2017   
26  Current Policies  Ontario                   Oil  Primary Fuel  2018   
27  Current Policies  Ontario                   Oil  Primary Fuel  2019   
28  Current Policies  Ontario                   Oil  Primary Fuel  2020   
29  Current Policies  Ontario                   Oil  Primary Fuel  2021   
30  Current Policies  Ontario                 Solar  Primary Fuel  2016   
31  Current Policies  Ontario                 Solar  Primary Fuel  2017   
32  Current Policies  Ontario                 Solar  Primary Fuel  2018   
33  Current Policies  Ontario                 Solar  Primary Fuel  2019   
34  Current Policies  Ontario                 Solar  Primary Fuel  2020   
35  Current Policies  Ontario                 Solar  Primary Fuel  2021   
36  Current Policies  Ontario               Uranium  Primary Fuel  2016   
37  Current Policies  Ontario               Uranium  Primary Fuel  2017   
38  Current Policies  Ontario               Uranium  Primary Fuel  2018   
39  Current Policies  Ontario               Uranium  Primary Fuel  2019   
40  Current Policies  Ontario               Uranium  Primary Fuel  2020   
41  Current Policies  Ontario               Uranium  Primary Fuel  2021   
42  Current Policies  Ontario                  Wind  Primary Fuel  2016   
43  Current Policies  Ontario                  Wind  Primary Fuel  2017   
44  Current Policies  Ontario                  Wind  Primary Fuel  2018   
45  Current Policies  Ontario                  Wind  Primary Fuel  2019   
46  Current Policies  Ontario                  Wind  Primary Fuel  2020   
47  Current Policies  Ontario                  Wind  Primary Fuel  2021   

         Value  
0    1444.1490  
1     962.0511  
2    1310.7740  
3    1249.3920  
4     756.0698  
5     756.0790  
6       0.0000  
7       0.0000  
8       0.0000  
9       0.0000  
10      0.0000  
11      0.0000  
12  36513.0000  
13  40016.0100  
14  38280.9900  
15  36210.0200  
16  36151.9800  
17  36151.9500  
18  14862.200

Use a SQL join to combine the capacity and creation of both dataframes or tables. Stored results in df_10.

In [65]:


df_10 = _deepnote_execute_sql("""SELECT c.Scenario, c.Region, c.Year, c.Variable,
c.Value AS E_capacity, g.Value AS E_generate

FROM Capacity c 
JOIN Generate g
ON  c.Variable=g.Variable
AND c.Year=g.Year;

""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_10

Scenario   Region  Year              Variable  E_capacity  \
0   Current Policies  Ontario  2016  Biomass / Geothermal     801.300   
1   Current Policies  Ontario  2017  Biomass / Geothermal     692.700   
2   Current Policies  Ontario  2018  Biomass / Geothermal     692.700   
3   Current Policies  Ontario  2019  Biomass / Geothermal     492.700   
4   Current Policies  Ontario  2020  Biomass / Geothermal     492.700   
5   Current Policies  Ontario  2021  Biomass / Geothermal     492.700   
6   Current Policies  Ontario  2016           Coal & Coke       0.000   
7   Current Policies  Ontario  2017           Coal & Coke       0.000   
8   Current Policies  Ontario  2018           Coal & Coke       0.000   
9   Current Policies  Ontario  2019           Coal & Coke       0.000   
10  Current Policies  Ontario  2020           Coal & Coke       0.000   
11  Current Policies  Ontario  2021           Coal & Coke       0.000   
12  Current Policies  Ontario  2016  Hydro / Wave / Tidal    9105.298   
13  Current Policies  Ontario  2017  Hydro / Wave / Tidal    9161.298   
14  Current Policies  Ontario  2018  Hydro / Wave / Tidal    9161.298   
15  Current Policies  Ontario  2019  Hydro / Wave / Tidal    9161.298   
16  Current Policies  Ontario  2020  Hydro / Wave / Tidal    9161.298   
17  Current Policies  Ontario  2021  Hydro / Wave / Tidal    9161.298   
18  Current Policies  Ontario  2016           Natural Gas    9629.630   
19  Current Policies  Ontario  2017           Natural Gas    9918.631   
20  Current Policies  Ontario  2018           Natural Gas    9918.631   
21  Current Policies  Ontario  2019           Natural Gas    9918.631   
22  Current Policies  Ontario  2020           Natural Gas   10903.630   
23  Current Policies  Ontario  2021           Natural Gas   10903.630   
24  Current Policies  Ontario  2016                   Oil     250.450   
25  Current Policies  Ontario  2017                   Oil     250.450   
26  Current Policies  Ontario  2018                   Oil     250.450   
27  Current Policies  Ontario  2019                   Oil     250.450   
28  Current Policies  Ontario  2020                   Oil     250.450   
29  Current Policies  Ontario  2021                   Oil     250.450   
30  Current Policies  Ontario  2016                 Solar    2400.460   
31  Current Policies  Ontario  2017                 Solar    2580.460   
32  Current Policies  Ontario  2018                 Solar    2669.460   
33  Current Policies  Ontario  2019                 Solar    2669.460   
34  Current Policies  Ontario  2020                 Solar    2669.460   
35  Current Policies  Ontario  2021                 Solar    2669.460   
36  Current Policies  Ontario  2016               Uranium   13568.000   
37  Current Policies  Ontario  2017               Uranium   12633.000   
38  Current Policies  Ontario  2018               Uranium   12633.000   
39  Current Policies  Ontario  2019               Uranium   12633.000   
40  Current Policies  Ontario  2020               Uranium   11808.000   
41  Current Policies  Ontario  2021               Uranium   11808.000   
42  Current Policies  Ontario  2016                  Wind    4841.450   
43  Current Policies  Ontario  2017                  Wind    5115.450   
44  Current Policies  Ontario  2018                  Wind    5076.450   
45  Current Policies  Ontario  2019                  Wind    5076.450   
46  Current Policies  Ontario  2020                  Wind    5376.449   
47  Current Policies  Ontario  2021                  Wind    5536.450   

    E_generate  
0    1444.1490  
1     962.0511  
2    1310.7740  
3    1249.3920  
4     756.0698  
5     756.0790  
6       0.0000  
7       0.0000  
8       0.0000  
9       0.0000  
10      0.0000  
11      0.0000  
12  36513.0000  
13  40016.0100  
14  38280.9900  
15  36210.0200  
16  36151.9800  
17  36151.9500  
18  14862.2000  
19   8378.6150  
20  11831.2200  
21  11504.1700  
22  12122.1600  
23  13899.7900  
24    544

Uranium has the largest capacity with 75083 TWh and produces the most power (519808.55 TWh total) than any other resource..

Natural gas comes fourth in terms of energy generation, but it has the second-highest power capacity with 61192.783 TWh. In other hand,  Hydro holds the second-place position in the generation of electricity followed by wind and natural gas.

In [66]:
_deepnote_run_altair(df_10, """{"data":{"name":"placeholder"},"mark":{"type":"bar","tooltip":true},"height":220,"$schema":"https://vega.github.io/schema/vega-lite/v4.json","autosize":{"type":"fit"},"encoding":{"x":{"sort":{"order":"descending","encoding":"y"},"type":"nominal","field":"Variable","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"quantitative","field":"E_capacity","scale":{"type":"linear","zero":true},"aggregate":"sum"},"color":{"sort":null,"type":"nominal","field":"","scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

In [67]:
_deepnote_run_altair(df_10, """{"data":{"name":"placeholder"},"mark":{"type":"bar","tooltip":true},"height":220,"$schema":"https://vega.github.io/schema/vega-lite/v4.json","autosize":{"type":"fit"},"encoding":{"x":{"sort":{"order":"descending","encoding":"y"},"type":"nominal","field":"Variable","scale":{"type":"linear","zero":false}},"y":{"sort":null,"type":"quantitative","field":"E_generate","scale":{"type":"linear","zero":true},"aggregate":"sum"},"color":{"sort":null,"type":"nominal","field":"","scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

In [68]:
df_10.groupby(['Variable'])[['E_capacity','E_generate']].mean()

E_capacity    E_generate
Variable                                        
Biomass / Geothermal    610.800000   1079.752483
Coal & Coke               0.000000      0.000000
Hydro / Wave / Tidal   9151.964667  37220.658333
Natural Gas           10198.797167  12099.692500
Oil                     250.450000    326.352833
Solar                  2609.793333   2073.500000
Uranium               12513.833333  86634.758333
Wind                   5170.449833  12396.041667

## Now..... The Power of Subquery Applied Here 

In [69]:


df_U = _deepnote_execute_sql("""SELECT *
FROM

(
SELECT c.Scenario, c.Region, c.Year, c.Variable,
c.Value AS E_capacity, g.Value AS E_generate

FROM electricity_capacity c 
 JOIN electricity_generation g
ON  c.Variable=g.Variable
AND c.Year=g.Year
AND c.Scenario=g.Scenario
AND c.Region=g.Region
)


-- select uranium because uranium is highest energy producer as above analysis
WHERE Scenario='Current Policies' AND Variable='Uranium' AND Region='Ontario' AND Scenario='Current Policies' 
AND Year BETWEEN 2016 AND 2021;
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_U

Scenario   Region  Year Variable  E_capacity  E_generate
0  Current Policies  Ontario  2016  Uranium     13568.0    91142.01
1  Current Policies  Ontario  2017  Uranium     12633.0    90445.00
2  Current Policies  Ontario  2018  Uranium     12633.0    90155.01
3  Current Policies  Ontario  2019  Uranium     12633.0    90454.00
4  Current Policies  Ontario  2020  Uranium     11808.0    80102.49
5  Current Policies  Ontario  2021  Uranium     11808.0    77510.04

In [70]:
df_U.groupby(['Scenario','Region','Variable'])[['E_capacity', 'E_generate']].mean()

E_capacity    E_generate
Scenario         Region  Variable                            
Current Policies Ontario Uranium   12513.833333  86634.758333

In [71]:
import plotly.express as px
px.histogram(df_10, x="E_generate", y="Variable",  template="ggplot2")


In [72]:
px.histogram(df_10, x="E_generate", y="Variable",  template="ggplot2")

### Simple Year filter for Electricity generation.

In [73]:
Year = 2018

In [74]:
#A = df_9[()]
#A = df_9[(df_9["Year"]>=2018)]
#A = df_9[(df_9["Year"]>=2018)]["E_capacity"].values



Year_generate = df_U[(df_U["Year"]==Year)]["E_generate"].values
Year_generate


array([90155.01])

In [82]:
print((Year_generate))

[90155.01]


### Simple Dropdown for electricity capacity (Years between 2016 to 2021).

In [36]:
Variable = 'Uranium'

In [75]:
Year_capacity = df_10[(df_10["Variable"]==Variable)]["E_capacity"].values 
Year_capacity

array([13568., 12633., 12633., 12633., 11808., 11808.])

In conclusion, I can examine a lot more potential data using Python and SQL.

- FInd average electricity interchange  between 2011 to 2021 in various regions. (don't include canada whole region).

In [76]:


df_i = _deepnote_execute_sql("""SELECT * FROM electricity_interchange 
WHERE 
Variable = 'Exports' AND
Region != 'Canada' AND
Scenario = 'Current Policies' AND
Year  BETWEEN 2011 AND 2021;
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_i

Scenario                     Region Variable  Year       Value
0    Current Policies                    Alberta  Exports  2011    128.4000
1    Current Policies           British Columbia  Exports  2011   9953.8900
2    Current Policies                   Manitoba  Exports  2011   9343.8100
3    Current Policies              New Brunswick  Exports  2011   1083.3500
4    Current Policies  Newfoundland and Labrador  Exports  2011      0.0000
..                ...                        ...      ...   ...         ...
105  Current Policies                Nova Scotia  Exports  2021      0.0000
106  Current Policies                    Ontario  Exports  2021  11646.8800
107  Current Policies       Prince Edward Island  Exports  2021      0.0000
108  Current Policies                     Quebec  Exports  2021  16963.8600
109  Current Policies               Saskatchewan  Exports  2021    244.5158

[110 rows x 5 columns]

In [80]:


df_11 = _deepnote_execute_sql("""SELECT *
FROM

(SELECT row_number() over (order by Value DESC) as inc, Scenario,Region,Variable,Year,Value
FROM df_i) x

WHERE inc BETWEEN 1 and 25;
""", 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_11

inc          Scenario            Region Variable  Year        Value
0     1  Current Policies            Quebec  Exports  2013  29541.00000
1     2  Current Policies            Quebec  Exports  2017  27649.58000
2     3  Current Policies            Quebec  Exports  2018  27022.21200
3     4  Current Policies            Quebec  Exports  2016  25541.00000
4     5  Current Policies            Quebec  Exports  2020  24371.76900
5     6  Current Policies            Quebec  Exports  2012  24038.00000
6     7  Current Policies            Quebec  Exports  2014  23587.45000
7     8  Current Policies            Quebec  Exports  2015  23533.00000
8     9  Current Policies           Ontario  Exports  2019  20894.13000
9    10  Current Policies           Ontario  Exports  2016  20488.00000
10   11  Current Policies           Ontario  Exports  2015  20142.00000
11   12  Current Policies            Quebec  Exports  2011  19879.00000
12   13  Current Policies           Ontario  Exports  2020  17649.24518
13   14  Current Policies           Ontario  Exports  2014  17082.92000
14   15  Current Policies           Ontario  Exports  2018  17015.69200
15   16  Current Policies            Quebec  Exports  2021  16963.86000
16   17  Current Policies           Ontario  Exports  2017  16953.85000
17   18  Current Policies  British Columbia  Exports  2017  13974.00000
18   19  Current Policies           Ontario  Exports  2012  13823.00000
19   20  Current Policies  British Columbia  Exports  2016  13720.00000
20   21  Current Policies  British Columbia  Exports  2015  12392.00000
21   22  Current Policies  British Columbia  Exports  2020  11680.58179
22   23  Current Policies           Ontario  Exports  2021  11646.88000
23   24  Current Policies            Quebec  Exports  2019  11329.18000
24   25  Current Policies  British Columbia  Exports  2012  11065.28000

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=7532f9e0-0efa-442b-8fbe-94e67bc1fb7e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>